import Rights from './rights';

export default {
    GET_EMPLOYEES: Rights.VIEW_EMPLOYEES,
    GET_EMPLOYEE: Rights.VIEW_EMPLOYEES,
    CREATE_EMPLOYEE: Rights.EDIT_EMPLOYEES,
    UPDATE_EMPLOYEE: Rights.EDIT_EMPLOYEES,
    EDIT_USERS: Rights.EDIT_USERS,
    GET_ROLES: Rights.VIEW_ROLES,
    GET_ROLE: Rights.VIEW_ROLES,
    CREATE_ROLE: Rights.EDIT_ROLES,
    UPDATE_ROLE: Rights.EDIT_ROLES,
    GET_RIGHTS: Rights.VIEW_ROLES,
    EDIT_MOTIVATION: Rights.CONTROL_MOTIVATION_PROGRAMS,
    VIEW_MOTIVATION: Rights.VIEW_MOTIVATION_PROGRAMS,
    PARTICIPATE_MOTIVATION: Rights.TAKE_PART_IN_MOTIVATION_PROGRAMS,
    RESET_CLIENT_PASSWORD: Rights.RESET_CLIENT_PASSWORD,
    MOTIVATION_REPORT_CREATE: Rights.MOTIVATION_REPORT_CREATE,
    SET_PAYED_AND_FINISHED_STATUS: Rights.SET_PAYED_AND_FINISHED_STATUS
};

